spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/neoguri_db?useUnicode=true&serverTimeZone=Asia/Seoul'
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hiberneate:
        format_sql: true

logging:
  level:
    org:
      hibernate: info
