spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/neoguri_db?useUnicode=true&serverTimeZone=Asia/Seoul&case'
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
  liquibase:
    user: liquibase
    password: neoguri123!
    default-schema: neoguri_db
    database-change-log-table: database_change_log
    database-change-log-lock-table: database_change_log_lock
    enabled: true
    change-log: classpath:migrations/changelog-master.yaml

logging:
  pattern:
    console: "[%d{YYYY-MM-dd HH:mm:ss}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      hibernate: info

neoguri:
  jwt:
    secret: 'asljdfhalksdjhfklasdjfkasdfbkasjdhbkajshbvkhscbvaisufvghoasfdguyoiasbigb248t92bgoib0g9278rytg901b3flkh1bfejkhvasudvc67c8v7s8asljdfhalksdjhfklasdjfkasdfbkasjdhbkajshbvkhscbvaisufvghoasfdguyoiasbigb248t92bgoib0g9278rytg901b3flkh1bfejkhvasudvc67c8v7s8asdfivb34'
    duration:
      access-token: 60 # minutes, 1 hour
      refresh-token: 10080 # minutes, = 7 days

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true